utoipa-axum: Allow trailing comma in `routes!()` macro
juhaku/utoipa pull request #1238
Opened 2024-12-13 09:22 UTC by Turbo87

Once the `routes!()` invocation contains more than a couple of routes, it is likely that each route will be on its own line. Currently, the macro does not support trailing commas, which causes the git diff when adding a new route to be unnecessarily large. With this change trailing commas are supported, which shrinks the diff down to a single-line change.

2024-12-13 09:40 UTC, Turbo87 commented
Admittedly, I misunderstood from the documentation that `.routes(routes!(...))` is supposed to be called per-endpoint instead of having one long list... but this change IMHO still seems useful :D

2024-12-16 10:12 UTC, Turbo87 commented
@juhaku any thoughts on this? :)

2024-12-16 16:39 UTC, juhaku commented
Well, I don't have a strong opinion on trailing comma. Though with such support users can decide whether they want to use the trailing comma or not, so why not.

2024-12-16 16:42 UTC, juhaku requested changes
Small and simple, just needs CHANGELOG.md entry. Newest entry to the top. This should come under title `Unreleased` and sub title `Changed`. 

Also seems to need `cargo fmt`. I should setup pre commit hook, but haven't got it done :smiling_face_with_tear:

2024-12-16 16:53 UTC, Turbo87 commented
rebased and feedback addressed :)

2024-12-16 17:12 UTC, juhaku approved these changes
Seems solid, thanks :100:

2024-12-16 19:17 UTC, merged