Axum 0.7 bindings
juhaku/utoipa pull request #807
Opened 2023-11-27 09:48 UTC by Libbum

Hi! First contribution to this repo, so may have missed some things.

Axum 0.7 just got released which has some breaking changes to bring everything up to date with hyper 1.0.

The main consequence for utoipa is the removal of hyper's `HttpBody` from `Router`.

2023-11-27 22:23 UTC, juhaku commented
With this update, there are examples with the axum 0.6 that should be also upgraded, but that can be another PR.

2023-11-27 22:41 UTC, Libbum commented
Ah, yes. If you mean just the `examples/todo-axum` demo, I can do that tomorrow morning.

2023-11-27 23:40 UTC, juhaku commented
> Ah, yes. If you mean just the `examples/todo-axum` demo, I can do that tomorrow morning.

Yes, that one indeed. :slightly_smiling_face:

2023-11-27 23:42 UTC, juhaku approved these changes
Looks good to me

2023-11-27 23:52 UTC, juhaku requested changes
Just one thing actually, the REAMDE.md, should be changed as well for `utoipa-swagger-ui` and `utoipa-redoc` and `utoipa-rapidoc` with the same changes as the `src/lib.rs` by removing the `B` attribute. Also the latest minimum version should be updated to `0.7` in these READMEs.

2023-11-28 08:41 UTC, Libbum commented
Sweet, that should all be done now :smile:

2023-11-28 09:57 UTC, juhaku approved these changes
Super :tada:

2023-11-28 10:09 UTC, merged